# predict ecological integrity raster with xgb model
# over shapefile with superpixels generated by slic algorithm

library('tidyverse')
library('xgboost')
library('fastDummies')
library('terra')
library('ggplot2')
library('caret')
library('sf')
library('fasterize')

set.seed <- 1

input_folder <- 'data/model_input/slic'
output_folder <- 'output'
mask_file <- 'data/sources/mex_mask/Mask_IE2018.tif'

# read data
df <- read_csv(paste0(input_folder,'/df_xgb_input_slic.csv')) 
sf <- terra::vect(paste0(input_folder,'/slic.shp'))
r_mask <- terra::rast(mask_file)
xgb.fit <- xgb.load(paste0(output_folder,'/xgb slic v3/xgb.fit'))

df <- df %>% 
  select_if(!names(.) %in% c('hemerobia'))

df <- df %>% 
  drop_na()

df <- df  %>% 
  mutate(across(all_of(categorical_variables), as.factor))

# Create dummy variables:
df <- dummy_cols(df, select_columns =categorical_variables)

# Transform the two data sets into xgb.Matrix
xgb.matrix <- xgb.DMatrix(data=as.matrix(df %>% 
                                          select(-c('ID',
                                                    categorical_variables))))

# Predict outcomes
xgb.pred <- as.data.frame(predict(xgb.fit,xgb.matrix,reshape=T))
colnames(xgb.pred) <- c(seq(1,16,by=1),18)
df$prediction <- as.numeric(colnames(xgb.pred)[apply(xgb.pred,1,which.max)])

# Add missing IDs
df_aux <- as.data.frame(1:max(df$ID))
names(df_aux) <- 'ID'
df <- df %>% 
  right_join(df_aux) %>% 
  arrange(ID)

# Create raster
sf$prediction <- as.numeric(df$prediction)
r_pred <- rasterize(sf, r_mask, field="prediction")
plot(-r_pred)
writeRaster(r_pred, paste0(output_folder,'/ie_xgb_slic_2018.tif'), 
            overwrite=TRUE)