# Creates shapefile with superpixels generated by SLIC algorithm
# based on raster values

library(supercells)
library(terra)
library(sf)

input_folder <- 'data/model_input/rasters'
output_folder <- 'data/model_input/slic/2017'

# Read rasters
r_vh <- terra::rast(paste0(input_folder,'/vh.tif'))
r_vv <- terra::rast(paste0(input_folder,'/vv.tif'))
r_modis_mean <- terra::rast(paste0(input_folder,'/modis_mean.tif'))
r_modis_sd <- terra::rast(paste0(input_folder,'/modis_sd.tif'))
r_rast <- c(r_vh, r_vv, r_modis_mean, r_modis_sd)

# Run SLIC
r_rast_slic <- supercells(r_rast, k = 8e+06, compactness = 1)

# Save shapefile
sf <- st_geometry(r_rast_slic)
st_write(sf, paste0(output_folder,"/slic.shp"), append=FALSE)